version: '3'

services:
    #PHP Service
    laravel_scrubber_demo:
        build:
            context: ""
            dockerfile: Dockerfile
        container_name: laravel_scrubber_demo
        tty: true
        environment:
            SERVICE_NAME: laravel_scrubber_demo
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ../.:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - yorcreative

    #Nginx Service
    laravel_scrubber_demo-webserver:
        image: nginx:alpine
        container_name: laravel_scrubber_demo-webserver
        tty: true
        ports:
            - "9787:81"
            - "6655:443"
        volumes:
            - ../.:/var/www/
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            - yorcreative
        depends_on:
            - laravel_scrubber_demo

    laravel_scrubber_demo-db:
        image: mysql:5.7.22
        container_name: laravel_scrubber_demo-db
        restart: unless-stopped
        tty: true
        ports:
            - "3332:3306"
        environment:
            MYSQL_DATABASE: laravel_scrubber_demo
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: laravel_scrubber_demo-mysql
        volumes:
            - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - ./dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - yorcreative
networks:
    yorcreative:
        driver: bridge
